### PR TITLE
add xen sublibrary to be used with MirageOS/Xen

### PR DESCRIPTION
**Pull request by hannesm**
In order to use `bin_prot` on MirageOS/Xen, the included C files need to be recompiled with other flags (namely `-mno-red-zone` (since running in kernel mode, where there is no red zone) and no system-wide includes).

This patch adds a sublibrary `bin_prot.xen`, consisting of no ML modules, but solely for the purpose of providing the compiled and linked C files.  Since OCamlbuild does only compile each target once, symbolic links are created for the C files.

### CODE REVIEW

**Comment by samoht** [comment]
This is needed to compile and run Irmin on Xen. We used to have [patched versions](https://github.com/mirage/mirage-dev/tree/master/packages/bin_prot) but that'd be definitely nicer to integrate that upstream!

**Comment by diml** [comment]
Thanks! I'll get this integrated for the next release

**Comment by hannesm** [comment]
@diml hmm, seems like 113.03.03 didn't include this change, but instead changed the build system in a way that this patch does not apply anymore.

**Comment by diml** [comment]
Ah, I missed this patch in my todo list. Basically many of the files touched by this patch are generated by our public release process, so it's not straightforward to include it.

I imported the changes and added this  to 113.33.03

**Comment by hannesm** [comment]
@diml thx! :D

**Comment by diml** [comment]
I switched the build system to [jbuilder](https://github.com/janestreet/jbuilder) and reimplemented this feature. It should work but I didn't test

**Pull request closed without merging**
